### PR TITLE
Add docs build and deployment to GH Pages using GH Actions

### PR DESCRIPTION
**Pull request by rajkumardongre**

### CODE REVIEW

**Comment by interkosmos** [comment]
LGTM. 👍

**Comment by milancurcic** [comment]
Thanks @rajkumardongre. Were you able to test the deployed pages on your fork?

**Comment by rajkumardongre** [comment]
I am getting this error :
```
HEAD is now at [61](https://github.com/rajkumardongre/http-client/actions/runs/5992687929/job/16350513487#step:6:62)95e05 Add docs build and deployment to GH Pages using GH Actions
/usr/bin/git checkout --orphan gh-pages
Switched to a new branch 'gh-pages'
/usr/bin/git reset --hard
/usr/bin/git commit --no-verify --allow-empty -m Initial gh-pages commit
[gh-pages (root-commit) 6102d79] Initial gh-pages commit
/usr/bin/git push --force ***github.com/rajkumardongre/http-client.git gh-pages
remote: Permission to rajkumardongre/http-client.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/rajkumardongre/http-client.git/': The requested URL returned error: 403
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
fatal: 'github-pages-deploy-action-temp-deployment-folder' is not a working tree
Error: The process '/usr/bin/git' failed with exit code 128
Deployment failed!
```

**Comment by rajkumardongre** [comment]
I realized that I hadn't granted the read-and-write permission under the settings > general > workflow permissions. I have now updated the permission, and everything is functioning correctly.

Here is the Link: https://rajkumardongre.github.io/http-client/

**Comment by milancurcic** [comment]
Excellent, let's merge. I think the permissions should be in place here as is.

**Review by milancurcic — APPROVED** [review]

**Pull request merged**
